<?php

/**
 * @file
 * Converts static HTML to a JQuery UI Accordion or Tabs widget.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function jquery_ui_filter_theme() {
  return [
    'jquery_ui_filter' => [
      'variables' => [
        'role' => 'accordion',
        'options' => [],
        'content' => NULL,
      ],
    ]
  ];
}

/**
 * Prepares variables for jQuery UI filter template.
 *
 * Default template: jquery_ui_filter.html.twig.
 *
 * @param $variables
 *   An associative array containing:
 *   - role: The jQuery UI widget type, accordion or tabs.
 *   - options: The jQuery UI filter options which will be converted to
 *     attributes.
 *   - content: The HTML content to be converted into a jQuery UI widget.
 */
function template_preprocess_jquery_ui_filter(&$variables) {
  // Set data-ui-* attributes from role and options.
  $attributes = [
    'data-ui-role' => $variables['role'],
  ];
  foreach ($variables['options'] as $name => $value) {
    $attributes['data-ui-' . $name] = $value;
  }
  $variables['attributes'] = new Attribute($attributes);

  // Attached library and settings.
  $variables['#attached']['library'][] = 'jquery_ui_filter/jquery_ui_filter';
  $variables['#attached']['drupalSettings'][] = ['jquery_ui_filter' => \Drupal::config('jquery_ui_filter.settings')->get()];
}
